### ISSUE TITLE
tunner_easy.py - Permission Denied

### ISSUE THREAD

**Issue by kb1lqd** [hdkmike/simple-tuntap#1]
@hdkmike I ran tunnel_easy.py on my raspberry PI and got this error message:

``` python
kb1lqd@raspberrypi:~/Documents/hdkmike_tuntap/simple-tuntap/src $ python tunnel_easy.py 
tunnel - DEBUG - Tunnel class created
pytun - DEBUG - Opening /dev/net/tun...
pytun - DEBUG - Opening TUN tunnel ''...
pytun - ERROR - Cannot open a TUN tunnel because the operation is not permitted.
Traceback (most recent call last):
  File "tunnel_easy.py", line 17, in <module>
    t = tunnel.Tunnel(mode='tun')
  File "/home/kb1lqd/Documents/hdkmike_tuntap/simple-tuntap/src/tunnel.py", line 29, in __init__
    self._tun = pytun.open(tunmode)
  File "/home/kb1lqd/.local/lib/python2.7/site-packages/pytun.py", line 82, in __init__
    self.open()
  File "/home/kb1lqd/.local/lib/python2.7/site-packages/pytun.py", line 118, in open
    raise self.NotPermitted()
pytun.NotPermitted
pytun - DEBUG - Closing tunnel ''...
pytun - INFO - Tunnel '' closed.
```

I'm NOT running in a virtual python environment and when I tried `sudo` I got : 

``` python
kb1lqd@raspberrypi:~/Documents/hdkmike_tuntap/simple-tuntap/src $ sudo python tunnel_easy.py 
Traceback (most recent call last):
  File "tunnel_easy.py", line 2, in <module>
    import dpkt
ImportError: No module named dpkt
```

Which doesn't make since because I could run without sudo as dpkt IS installed. Do I have permission errors occurring?

Thanks,

- Brent

**Comment by hdkmike** [comment]
@kb1lqd , it definitely requires root privileges to run. Since it was a simple little program, I didn't include a guard for that. 

As for `dpkt` missing, that's an odd one. The only thing I can think of is that your `PYTHONPATH` env is not picking up in your `sudo` session.

**Comment by hdkmike** [comment]
What distro are you running on your Pi?

**Comment by kb1lqd** [comment]
Standard raspian

**Comment by hdkmike** [comment]
Check your permissions for dpkt: `/usr/local/lib/python2.7/dist-packages/dpkt/`. I think it should be `755`.

**Comment by hdkmike** [comment]
Correction: `755` on the folder and 644 on the py/pyc files inside.

**Comment by hdkmike** [comment]
My owner user  is `root` and my group is `staff`. Not sure what Raspbian is up to these days.

**Comment by hdkmike** [comment]
This _shouldn't_ happen as root though.

**Comment by kb1lqd** [comment]
Ok will do, I'm not home right now but will do once home.

Also just so we are in the same page the output of this software will be
stream of bytes/packets at the layer 3 level? I could run two instances and
"connect" then as two devices on a single computer to test with a simple
loop program between them simulating and serial connection?

**Comment by hdkmike** [comment]
I'm not so sure it's the permissions... but let's debug. I'll try and keep on top of this.

**Comment by hdkmike** [comment]
So, not exactly. This script has all the necessary elements to do that. I didn't go farther than that because I wanted to make sure I understood the direction you want to take. I'll check your docs that you put up (https://github.com/kb1lqd/Faraday-Network-Interface-Docs).  This app just receives L3 packets and echos them back switching only dst and src IPs. Kinda "dumb" but you can see stuff in tshark/tcpdump. 

Yes, it's completely achievable to create two of these, then shuttle all the data across serial easily. This basically provides a file object that is the tun adapter. With `select`, we can _easily_ broker data between the tun file object and the serial file descriptor or file object.

**Comment by kb1lqd** [comment]
@hdkmike it looks like simply file permissions didn't work:

``` bash
kb1lqd@raspberrypi:~/Documents/hdkmike_tuntap/simple-tuntap/src $ sudo chmod 755 ../src/
kb1lqd@raspberrypi:~/Documents/hdkmike_tuntap/simple-tuntap/src $ sudo python tunnel_easy.py
Traceback (most recent call last):
  File "tunnel_easy.py", line 2, in <module>
    import dpkt
ImportError: No module named dpkt
kb1lqd@raspberrypi:~/Documents/hdkmike_tuntap/simple-tuntap/src $ sudo chmod 644 tunnel_easy.py
kb1lqd@raspberrypi:~/Documents/hdkmike_tuntap/simple-tuntap/src $ sudo python tunnel_easy.py
Traceback (most recent call last):
  File "tunnel_easy.py", line 2, in <module>
    import dpkt
ImportError: No module named dpkt
```

**Comment by kb1lqd** [comment]
I tried adding user to `netdev` and did not work.

**Comment by kb1lqd** [comment]
@hdkmike I was able to get somewhere with this!


``` bash
kb1lqd@raspberrypi:~/Documents/hdkmike_tuntap/simple-tuntap/src $ sudo apt-get install python-dpkt
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  python-dumbnet
The following NEW packages will be installed:
  python-dpkt python-dumbnet
0 upgraded, 2 newly installed, 0 to remove and 26 not upgraded.
Need to get 120 kB of archives.
After this operation, 555 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://raspbian.mirrors.lucidnetworks.net/raspbian stretch/main armhf python-dumbnet armhf 1.12-7 [52.0 kB]
Get:2 http://mirrors.syringanetworks.net/raspbian/raspbian stretch/main armhf python-dpkt all 1.8.r98-0.1 [68.3 kB]
Fetched 120 kB in 1s (83.9 kB/s)
Selecting previously unselected package python-dumbnet.
(Reading database ... 122776 files and directories currently installed.)
Preparing to unpack .../python-dumbnet_1.12-7_armhf.deb ...
Unpacking python-dumbnet (1.12-7) ...
Selecting previously unselected package python-dpkt.
Preparing to unpack .../python-dpkt_1.8.r98-0.1_all.deb ...
Unpacking python-dpkt (1.8.r98-0.1) ...
Setting up python-dumbnet (1.12-7) ...
Setting up python-dpkt (1.8.r98-0.1) ...
kb1lqd@raspberrypi:~/Documents/hdkmike_tuntap/simple-tuntap/src $ sudo python tunnel_easy.py
Traceback (most recent call last):
  File "tunnel_easy.py", line 6, in <module>
    import tunnel
  File "/home/kb1lqd/Documents/hdkmike_tuntap/simple-tuntap/src/tunnel.py", line 6, in <module>
    import pytun
ImportError: No module named pytun

```

https://stackoverflow.com/questions/21457250/error-while-using-dpkt-in-python

Now I need to figure out why pytun isn't importing.

**Comment by kb1lqd** [comment]
OK I `sudo pip install pytun` and now that issues seems to be cleared up:

``` bash
kb1lqd@raspberrypi:~/Documents/hdkmike_tuntap/simple-tuntap/src $ sudo python tunnel_easy.py
tunnel - DEBUG - Tunnel class created
pytun - DEBUG - Opening /dev/net/tun...
pytun - DEBUG - Opening TUN tunnel ''...
pytun - INFO - Tunnel 'tun0' opened.
tunnel - INFO - Monitoring socket...
Wait indefinitely. Press ctrl-c to quit.tunnel - DEBUG - Handling packet...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kb1lqd/Documents/hdkmike_tuntap/simple-tuntap/src/tunnel.py", line 58, in _monitor_socket
    self._handler(data)
  File "tunnel_easy.py", line 25, in echohandler
    ip_pkt = dpkt.ip.IP(data)
  File "/usr/lib/python2.7/dist-packages/dpkt/dpkt.py", line 72, in __init__
    self.unpack(args[0])
  File "/usr/lib/python2.7/dist-packages/dpkt/ip.py", line 56, in unpack
    raise dpkt.UnpackError, 'invalid header length'
UnpackError: invalid header length
```

but this error didn't quit the program. it's running.

**Comment by kb1lqd** [comment]
`ping` doesn't work when I am logged into another ssh session (not sure about local session). From the second ssh session I see the `tun0` adapter:

``` bash
kb1lqd@raspberrypi:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.50  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 2606:6000:6313:7d00:5370:c03:9558:6db1  prefixlen 64  scopeid 0x0<global>
        inet6 2606:6000:6313:7d00::5  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::8675:9607:96b7:bb19  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:d1:ef:d5  txqueuelen 1000  (Ethernet)
        RX packets 165051  bytes 41593528 (39.6 MiB)
        RX errors 0  dropped 8  overruns 0  frame 0
        TX packets 65684  bytes 10447898 (9.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 93  bytes 5564 (5.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 93  bytes 5564 (5.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 192.168.40.1  netmask 255.255.255.255  destination 192.168.40.1
        inet6 fe80::ccd1:5618:64a1:47e8  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1  bytes 48 (48.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b8:27:eb:84:ba:80  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

kb1lqd@raspberrypi:~ $
```

**Comment by hdkmike** [comment]
That's strange why the dependencies didn't work. Glad you got it running now.

**Comment by hdkmike** [comment]
The program crashed because my crappy handler. It makes too many assumptions.
